Hexagon: add rev test for different combinations of cpu and machine
The test also checks for the expected warning on stderr when the used
revision is different from the compiled binary.

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>

diff --git a/tests/tcg/hexagon/Makefile.quic-softmmu-target b/tests/tcg/hexagon/Makefile.quic-softmmu-target
--- a/tests/tcg/hexagon/Makefile.quic-softmmu-target
+++ b/tests/tcg/hexagon/Makefile.quic-softmmu-target
@@ -204,6 +204,7 @@ multiple_writes.o: multiple_writes.c mmu.h
 multiple_writes: multiple_writes.o
 thread_scheduling: thread_scheduling.o thread_common.o
 rev: rev.o
+rev.o: EXTRA_TEST_CFLAGS=-mv73
 pmu: pmu.o thread_common.o
 start.o: start.c mmu.h
 start: start.o thread_common.o
@@ -293,13 +294,39 @@ run-gregs: gregs
 		_$<.stderr > _$<.stderr.filtered
 	diff $(HEXAGON_SYSTEM_SRC)/expected-gregs-warnings.txt _$<.stderr.filtered
 
-run-rev: run-rev-0x67 run-rev-0x73 run-rev-0x75
-run-rev-0x67: QEMU_EXTRA_OPTS=-M V73NA_1024 -cpu v67
-run-rev-0x73: QEMU_EXTRA_OPTS=-M V73NA_1024
-run-rev-0x75: QEMU_EXTRA_OPTS=-M V75NA_1024 -cpu any
-run-rev-0x67 run-rev-0x73 run-rev-0x75: rev
-	$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $< >_$@.out ,"$< on $(TARGET_NAME) $(@:run-$<-%=%)")
-	grep -F "$(@:run-$<-%=%)" _$@.out
+# Test combinations, with expected output separated by a ':'
+#
+REV_TEST_COMBINATIONS="-M V69NA_1024           : 0x69" \
+		      "-cpu any                : 0x73" \
+		      "-cpu v69                : 0x69" \
+		      "-cpu v73 -M V69NA_1024  : 0x73" \
+		      "-cpu v69 -M V73NA_1024  : 0x69" \
+		      "-cpu any -M V69NA_1024  : 0x69" \
+		      "-cpu any -M V73NA_1024  : 0x73"
+
+run-rev: rev
+	@i=0; \
+	ret=0; \
+	for comb in $(REV_TEST_COMBINATIONS); do \
+		opt="$$(echo "$$comb" | cut -d: -f1)"; \
+		exp="$$(echo "$$comb" | cut -d: -f2)"; \
+		$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $< $$opt \
+			>$@.$$i.out 2>$@.$$i.err, $< on $(TARGET_NAME) ($$i)) && \
+		grep -qF $$exp $@.$$i.out; \
+		err=$$?; \
+		if test $$exp != 0x73; then \
+			grep -q 'warning: using .* cpu but binary is for v73' $@.$$i.err; \
+			err=$$(($$err + $$?)); \
+		fi; \
+		if test $$err -eq 0; then \
+			echo "  rev test $$i: OK"; \
+		else \
+			echo "  rev test $$i: FAIL"; \
+			ret=1; \
+		fi; \
+		i=$$(($$i + 1)); \
+	done; \
+	exit $$ret
 
 # Run some tests with paranoid-commit-state turned on
 
